---
- name: Install Zabbix 7.0 Agent on Ubuntu 24.04
  hosts: ubuntu_servers
  become: yes
  vars:
    zabbix_server_ip: "source ip"

  tasks:
    - name: Install prerequisites
      apt:
        name: [wget, gnupg]
        state: present
        update_cache: yes

    - name: Download Zabbix 7.0 release package for Ubuntu 24.04
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb"
        dest: "/tmp/zabbix-release.deb"
        mode: '0644'

    - name: Install Zabbix release package
      apt:
        deb: "/tmp/zabbix-release.deb"

    - name: Update apt cache after Zabbix repo added
      apt:
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent server IPs
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^({{ item.key }})='
        line: '{{ item.key }}={{ item.value }}'
        backup: yes
      loop:
        - { key: 'Server', value: '{{ zabbix_server_ip }}' }
        - { key: 'ServerActive', value: '{{ zabbix_server_ip }}' }

    - name: Ensure Zabbix Agent is enabled and restarted
      service:
        name: zabbix-agent
        enabled: yes
        state: restarted

    - name: Check Zabbix Agent version
      shell: zabbix_agentd -V | head -n 1
      register: zabbix_version_output
      ignore_errors: yes

    - name: Print Zabbix Agent version
      debug:
        msg: "Zabbix Agent version is {{ zabbix_version_output.stdout | default('Unknown') }}"
